Global:
  AdminPermission: "starlightcore.admin"
Features:
  # 使用桶时有一定几率破碎
  BreakableBucket:
    Enable: true
    Chance: 0.3
  # 载具可乘坐更多人
  MultiPassengerVehicles:
    Enable: true
    MaxPlayer: 20
  # 雷暴天气戴金属帽子的实体在树下有几率被雷击
  TreeThunder:
    Enable: true
    Chance: 0.2
    IntervalTicks: 100
    HelmetList:
      - IRON_HELMET
      - GOLDEN_HELMET
  # 有毒食品
  PoisonousFood:
    Enable: true
    IntervalTicks: 100
    # 1000 代表一个小时
    MinDeathTime: 1000
    MaxDeathTime: 24000
  # 使玩家只有在蹲下时才能拾取物品
  RealPickup:
    Enable: true
  UnsafeTNT:
    Enable: true
    # 哑火几率
    MisfireChange: 0.1
    # 殉爆几率
    SabotageChange: 0.1