Global:
  AdminPermission: "starlightcore.admin"
Features:
  # 使用桶时有一定几率破碎
  BreakableBucket:
    Enable: true
    Chance: 0.3
  # 载具可乘坐更多人
  Features:
    MultiPassengerVehicles:
      Enable: true
      MaxPlayer: -1