Global:
  AdminPermission: "starlightcore.admin"
Features:
  # 使用桶时有一定几率破碎
  BreakableBucket:
    Enable: true
    Chance: 0.3
  # 载具可乘坐更多人
  MultiPassengerVehicles:
    Enable: true
    MaxPlayer: 20
  # 雷暴天气戴金属帽子的实体在树下有几率被雷击
  TreeThunder:
    Enable: true
    Chance: 0.2
    IntervalTicks: 20
    HelmetList:
      - IRON_HELMET
      - GOLDEN_HELMET